/** PDF presentation follows the default French UI. Stable CSV keys remain machine-readable. */
const labels: Record<string, string> = {
  confirmed: 'Confirmé',
  pending: 'En attente',
  converted_estimate: 'Devis facturé',
  converted_invoice: 'Facture issue du devis',
  revenue: 'Ventes',
  collections: 'Encaissements confirmés',
  outstanding: 'Solde restant à encaisser',
  overdue: 'Impayés en retard',
  payment_methods: 'Modes de paiement',
  pending_cheques: 'Chèques en attente',
  vat: 'TVA',
  summary: 'Synthèse financière',
  sales_by_client: 'Ventes par client',
  sales_by_product: 'Ventes par produit',
  sales_by_category: 'Ventes par catégorie',
  estimates: 'Suivi des devis',
  deliveries: 'Activité des livraisons',
  aging: 'Ancienneté des créances',
  ranking: 'Répartition des ventes',
  methods: 'Répartition des encaissements',
  buyer_type: 'Nouveaux clients et clients récurrents',
  cohort: 'Devis émis pendant la période',
  outcome: 'État actuel des devis de la période',
  delivery_status: 'État actuel des livraisons de la période',
  delivery_billing: 'Bons livrés : lien avec une facture',
  weightKg: 'Poids connu des articles',
  variants: 'Articles vendus par variante',
  current: 'Non échu',
  '1_30': 'Retard de 1 à 30 jours',
  '31_60': 'Retard de 31 à 60 jours',
  '61_plus': 'Retard de plus de 60 jours',
  net: 'Montant HT',
  gross: 'Montant TTC',
  amount: 'Montant',
  quantity: 'Articles vendus',
  invoiced_gross: 'Facturé TTC',
  invoiced_net: 'Facturé HT',
  invoiced_vat: 'TVA facturée',
  average_unit_price: 'Prix moyen par article HT',
  unknown_weight_count: 'Lignes sans poids connu',
  planned_weight_kg: 'Poids prévu',
  delivered_weight_kg: 'Poids livré',
  issued_count: 'Devis émis',
  accepted_count: 'Devis acceptés',
  rejected_count: 'Devis refusés',
  expired_count: 'Devis expirés',
  converted_estimate_count: 'Devis facturés',
  converted_invoice_count: 'Factures issues de devis',
  issued: 'Émis',
  sent: 'Envoyé',
  accepted: 'Accepté',
  rejected: 'Refusé',
  expired: 'Expiré',
  superseded: 'Remplacé',
  cancelled: 'Annulé',
  invoiced: 'Facturé',
  draft: 'Brouillon',
  prepared: 'Préparé',
  delivered: 'Livré',
  acknowledged: 'Réceptionné',
  linked: 'Avec facture',
  unlinked: 'Sans facture',
  cash: 'Espèces',
  bank_transfer: 'Virement bancaire',
  cheque: 'Chèque',
  other: 'Autre',
  new: 'Nouveaux clients',
  first_time: 'Nouveaux clients',
  returning: 'Clients récurrents',
  first: 'Nouveaux clients',
  repeat: 'Clients récurrents',
}
export const frenchReportLabel = (key: string) => labels[key] ?? key.replaceAll('_', ' ')
